### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by enduro44** [Swedbank-SPP/swedbank-payment-portal#11]
**_cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)_**

Exception is returned by guzzlehttp curl_exec, when trying to execute "https://accreditation.datacash.com/Transaction/acq_a"

I am on v0.8.22

**Comment by Swedbank-SPP** [comment]
Hi, try this solution to this problem: https://stackoverflow.com/a/42123710
Check if your 'default_cert_file' cert file exists.

**Comment by enduro44** [comment]
Solution worked like a char. Tnx!
