### ISSUE TITLE
provide set currency method for HPS

### ISSUE THREAD

**Issue by code-quantum** [Swedbank-SPP/swedbank-payment-portal#13]
How to set currency for HPS paymant method?

$txnDetails = new TxnDetails(
            $riskAction,
            $merchantReferenceId,
            new Amount($purchaseAmount),
            new ThreeDSecure(
                'Order nr: ' . $merchantReferenceId,
                $this->callback_domain,
                new \DateTime()
            )
        );

If i looking at SwedbankPaymentPortal\SharedEntity\Amount class, I see that private $currency = 'EUR' is hardcoded and methods for modify currency is not provided.

**Comment by Swedbank-SPP** [comment]
Hello, unfortunately Swedbank Payment Portal doesn't support any other currencies, but only Euro at the moment. That's why a library do not allow to change currency code in Amount object.

**Comment by Swedbank-SPP** [comment]
It's unclear now when SPP will support multi currencies on HPS/HCC, but we'll update a library accordingly.
