### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by mstaniszczak** [Swedbank-SPP/swedbank-payment-portal#18]
Where can I found API documentation? I hav eto prepare integration with Swedbank, but with Python application. I got only link to this repo, and documentation "Swedbank Payment Portal PHP Library Documentation", but now I have to do reverse engineering. WIll be much easier to have documentation of "raw" API.

**Comment by maijs** [comment]
@mstaniszczak What was the reason for closing this issue? That would be much appreciated if a comment is added with a brief explanation upon closing/resolving of an issue.

**Comment by mstaniszczak** [comment]
So as there was no answer, I decide to close this ticket, as it was resolved by hmmm... workaround;-)
