### ISSUE TITLE
PayPal Live environment not working

### ISSUE THREAD

**Issue by jsakars** [Swedbank-SPP/swedbank-payment-portal#3]
We have been struggling with this for almost 2 weeks where SPP support and PayPal both blaming each other. As it turns out - this library is not fully production (live) ready.

There is a hardcoded PayPal sandbox URL - https://github.com/Swedbank-SPP/swedbank-payment-portal/blob/master/src/PayPal/CommunicationEntity/SetExpressCheckoutResponse/SetExpressCheckoutResponse.php#L239

Given method should return corresponding URL based on environment (sandbox or live)

Ping @Swedbank-SPP

**Comment by Swedbank-SPP** [comment]
Hi,

Thank you for finding this bug. We fixed and now is in commit: https://github.com/Swedbank-SPP/swedbank-payment-portal/commit/091931994c9a0edd9995b538c33c864dd1623b42
