### ISSUE TITLE
BankLinkService::handlePendingUnfinishedResponse() does not remove finished purchases

### ISSUE THREAD

**Issue by maijs** [Swedbank-SPP/swedbank-payment-portal#4]
I have a problem with `BankLinkService::checkPendingTransactions()` where transactions are not being removed from local transaction repository even if response from the gateway indicates that they are successful.

Steps to reproduce:

1. Initiate a payment with `$spp->getBankLinkGateway()->initPayment()` with (example) merchant reference `ABC`.
2. Complete the payment process, get back to the merchant's store, at which point the callback is executed.
3. Wait 30 minutes, cron will run `$spp->getBankLinkGateway()->checkPendingTransactions();` which will query the gateway for status of transaction with merchant reference `ABC`. That will trigger the callback in the same manner it did in step 2.
4. Repeat step 3.

`\SwedbankPaymentPortal\BankLink\BankLinkService::handlePendingUnfinishedResponse()` has the following [code](https://github.com/Swedbank-SPP/swedbank-payment-portal/blob/master/src/BankLink/BankLinkService.php#L267):

```php
$transactionResult = $this->getTransactionResultFromQueryResponse($response);

if ($transactionResult) {
    $callback = $container->getCallback();
    $callback->handleFinishedTransaction($transactionResult, $transactionFrame);
    $this->getTransactionRepository()->remove($merchantReference);
};

$container->addFrame($transactionFrame);
$this->getTransactionRepository()->persist($container);
```

On successful transaction result transaction with merchant reference is being removed from transaction repository (`->remove($merchantReference)`), but then again the container which is obtained with the merchant reference is persisted with `->persist($container)` which stores the transaction as pending again.

**Comment by Swedbank-SPP** [comment]
Thanks! Fixed.
